### ISSUE TITLE
Bubble sort review

### ISSUE THREAD

**Issue by dex157** [aadamss/evo-ts-bootcamp#1]
[src/App.tsx#L12](https://github.com/aadamss/evo-ts-bootcamp/blob/71455c3eab6bb177098b85b26adc07b1a27bfd7d/homeworks/01-bubble-sort/src/App.tsx#L12) — better to use `number`, or `returnType<typeof window.setTimeout>`. `setTimeout` is node js function from point of view typescript, because CRA has some problems in settings.
[src/App.tsx#L54](https://github.com/aadamss/evo-ts-bootcamp/blob/71455c3eab6bb177098b85b26adc07b1a27bfd7d/homeworks/01-bubble-sort/src/App.tsx#L54) `state.state` looks not very good 🤔
[src/App.tsx#L77](https://github.com/aadamss/evo-ts-bootcamp/blob/71455c3eab6bb177098b85b26adc07b1a27bfd7d/homeworks/01-bubble-sort/src/App.tsx#L77) in class components usually try to avoid creating functions in render. So, the quick fix here is `newGame={this.restartGame}`
[BubbleSorting.tsx#L2](https://github.com/aadamss/evo-ts-bootcamp/blob/71455c3eab6bb177098b85b26adc07b1a27bfd7d/homeworks/01-bubble-sort/src/Components/BubbleSorting.tsx#L2) omg, **fp-ts** I'm impressed 

In common clear solution, looks good!

**Comment by IAmArthurAdams** [comment]
Hello!
Thank you for the review and the comments! I went through them and fixed them!
